# introduction to numpy

In [1]:
import numpy as np

In [2]:
print("numpy version", np.__version__)

numpy version 1.18.5


In [11]:
#define array using np.array
arr_int = np.array([[1,2,3], [4,5,6]])
print(arr_int)
print("type:", type(arr_int),"shape",arr_int.shape)
print("axis 0:", arr_int.shape[0],"axis 1:", arr_int.shape[1])

arr1d_float = np.array([.1, .2, .3, .4])
print(arr1d_float)
print("type:", type(arr1d_float),"shape",arr1d_float.shape)
print("axis 0:", arr1d_float.shape[0])

arr3d_int = np.array([[[1,2], [3,4]], [[5,6],[7,8]]])
print(arr3d_int)

[[1 2 3]
 [4 5 6]]
type: <class 'numpy.ndarray'> shape (2, 3)
axis 0: 2 axis 1: 3
[0.1 0.2 0.3 0.4]
type: <class 'numpy.ndarray'> shape (4,)
axis 0: 4
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [4]:
print([[1,2,3], [4,5,6]])

[[1, 2, 3], [4, 5, 6]]


In [20]:
arr_zeros = np.zeros((2,3) ,dtype="int32")
print(arr_zeros, arr_zeros.dtype, type(arr_zeros))

arr_ones = np.ones((2,4))
print(arr_ones, arr_ones.dtype, type(arr_ones), arr_ones.shape)

arr_arange = np.arange(1, 10, 2)
print(arr_arange, arr_arange.dtype, type(arr_arange), arr_arange.shape)

arr_empty = np.empty((100,100))
print(arr_empty, arr_empty.dtype)

[[0 0 0]
 [0 0 0]] int32 <class 'numpy.ndarray'>
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]] float64 <class 'numpy.ndarray'> (2, 4)
[1 3 5 7 9] int32 <class 'numpy.ndarray'> (5,)
[[1.02055226e-311 1.02054554e-311 6.95187041e-310 ...             nan
              nan             nan]
 [3.91612999e-306 1.16657952e-301 2.73456188e-304 ...             nan
              nan 4.50155003e-294]
 [            nan             nan             nan ... 1.93774906e-304
              nan             nan]
 ...
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 ... 0.00000000e+000
  0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 ... 0.00000000e+000
  0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 ... 0.00000000e+000
  0.00000000e+000 0.00000000e+000]] float64


In [26]:
dummy_list = [[1,2,3], [4,5,6]]
print("list:", dummy_list)
print("array:", arr_int)

#indexing
print(dummy_list[0][0])
print(arr_int[0,0], arr_int[0, :2])
print(arr_int[::-1, ::-1])

list: [[1, 2, 3], [4, 5, 6]]
array: [[1 2 3]
 [4 5 6]]
1
1 [1 2]
[[6 5 4]
 [3 2 1]]


In [27]:
#ndim and size of ndarray
print("num of dimension:", arr_int.ndim)
print("num of dimension", arr3d_int.ndim)

print("total items", arr_int.size)
print("total items", arr3d_int.ndim)

num of dimension: 2
num of dimension 3
total items 6
total items 3


In [29]:
#flatten
print("before flatten:", arr_int)
print("after flatten", arr_int.flatten())

before flatten: [[1 2 3]
 [4 5 6]]
after flatten [1 2 3 4 5 6]


In [32]:
#append and delete
print(np.append(arr1d_float, [10,11,12]))
print(np.append(arr_int, [[10,11,12]], axis =0))

[ 0.1  0.2  0.3  0.4 10.  11.  12. ]
[[ 1  2  3]
 [ 4  5  6]
 [10 11 12]]


In [40]:
#append and delete
print(np.append(arr1d_float,[10,11,12]))
print(np.append(arr_int, [[10,11,12]], axis=0))
print(np.append(arr_int, [[10],[11]], axis =1))
print(np.append(arr_int, arr_int, axis =0))
print(np.append(arr_int, arr_int, axis =1))

print(np.concatenate([arr_int, arr_int, arr_int], axis=1))
print(np.concatenate([arr_int, arr_zeros], axis =0))

[ 0.1  0.2  0.3  0.4 10.  11.  12. ]
[[ 1  2  3]
 [ 4  5  6]
 [10 11 12]]
[[ 1  2  3 10]
 [ 4  5  6 11]]
[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]
[[1 2 3 1 2 3 1 2 3]
 [4 5 6 4 5 6 4 5 6]]
[[1 2 3]
 [4 5 6]
 [0 0 0]
 [0 0 0]]


In [42]:
print(arr3d_int)
print(np.delete(arr3d_int, 1, axis=0))
print(np.delete(arr3d_int, -1, axis =1))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[[1 2]
  [3 4]]]
[[[1 2]]

 [[5 6]]]


In [47]:
#reshape
print(arr3d_int)
#print(np.reshape(arr3d_int, (3, 4)))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [48]:
print(np.resize(arr3d_int, (5,2)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]
 [1 2]]


In [53]:
print(arr1d_float.shape)

arr2d_float = arr1d_float[:, np.newaxis]
print(arr2d_float, arr2d_float.shape)
print(arr1d_float[None])

print(arr3d_int[:,:,:,np.newaxis].shape)
print(arr3d_int[:, np.newaxis, :].shape)

(4,)
[[0.1]
 [0.2]
 [0.3]
 [0.4]] (4, 1)
[[0.1 0.2 0.3 0.4]]
(2, 2, 2, 1)
(2, 1, 2, 2)


In [54]:
#transpose
print(arr_int)
print(arr_int.T)
print(arr_int.reshape(arr_int.shape[1], arr_int.shape[0]))

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[[1 2]
 [3 4]
 [5 6]]


In [58]:
#mathematics operation
print(dummy_list + dummy_list)
print(arr_int + arr_int)
print(arr3d_int*10)
print(arr1d_float * arr1d_float)

[[1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6]]
[[ 2  4  6]
 [ 8 10 12]]
[[[10 20]
  [30 40]]

 [[50 60]
  [70 80]]]
[0.01 0.04 0.09 0.16]


In [59]:
print(arr1d_float, arr1d_float)
print(np.dot(arr1d_float, arr1d_float))
print(np.dot(arr3d_int,10))

[0.1 0.2 0.3 0.4] [0.1 0.2 0.3 0.4]
0.30000000000000004
[[[10 20]
  [30 40]]

 [[50 60]
  [70 80]]]


In [64]:
np.random.seed(1) #seed agar random sama
print(np.random.randint(10,size=(2,3)))
print(np.random.uniform(size=(10,10)))
print(np.random.randn())
print(np.random.normal(1., 10, size=(5,1)))

[[5 8 9]
 [5 0 0]]
[[0.39658073 0.38791074 0.66974604 0.93553907 0.84631092 0.31327352
  0.52454816 0.44345289 0.22957721 0.53441391]
 [0.91396202 0.45720481 0.43069857 0.93912779 0.77838924 0.71597052
  0.8027575  0.09280081 0.51815255 0.86502025]
 [0.82914691 0.82960336 0.27304997 0.0592432  0.67052804 0.59306552
  0.6716541  0.41178788 0.1975509  0.28962964]
 [0.14212014 0.78331447 0.41253884 0.03417131 0.62402999 0.66063573
  0.29849529 0.44613451 0.22212455 0.07336417]
 [0.46923853 0.09617226 0.90337017 0.11949047 0.52479938 0.083623
  0.91686133 0.91044838 0.29893011 0.58438912]
 [0.56591203 0.61393832 0.95653566 0.26097898 0.23101542 0.53344849
  0.94993814 0.49305959 0.54060051 0.7654851 ]
 [0.04534573 0.13996612 0.79240359 0.02980136 0.88312548 0.54078819
  0.44798018 0.89213587 0.37758434 0.53842469]
 [0.65229888 0.36126102 0.57100856 0.63783648 0.12631489 0.69020459
  0.6477494  0.35393909 0.76323305 0.35653172]
 [0.75278835 0.88134183 0.01166919 0.49810907 0.07379201 0.7869